### ISSUE TITLE
Track Head Pose (xyz+rpy)

### ISSUE THREAD

**Issue by tfvieira** [vannisson/PGI010-Digital-Image-Processing#3]
# TODO
- [x] Track head pose.
- [x] Improve virtual scene.

# References

- [MediaPipe-Face-Mesh metric-3d](https://github.com/google-ai-edge/mediapipe/wiki/MediaPipe-Face-Mesh#metric-3d-space).
- [Face landmark detection guide](https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker).
- [A Simple and efficient Face direction detection in React](https://medium.com/@sshadmand/a-simple-and-efficient-face-direction-detection-in-react-e02cd9d547e5).

# Videos
- [Testing Head Pose Estimation with Mediapipe](https://www.youtube.com/watch?v=Lx5Am0SOq0s).
- [Testing Head Tracking with MediaPipe and A-frame](https://www.youtube.com/watch?v=tGSu-MESBP0).

## Papers
- [Hands-Free Human–Robot Interaction Using Multimodal Gestures and Deep Learning in Wearable Mixed Reality](https://ieeexplore.ieee.org/document/9395580) (2021).
- [High Fidelity Motion Adaptive Face Reenactment](https://ieeexplore.ieee.org/document/10189755) (2022) -- _Forçando um pouco a barra_.

**Comment by vannisson** [comment]
Achei umas coisas interessantes, esse Opentrack é um software que aplica isso que estamos fazendo, só que com o foco em jogos:
- https://github.com/opentrack/opentrack
- https://github.com/AIRLegend/aitrack
- https://www.youtube.com/watch?v=NS7sqcuEcZ0

**Comment by vannisson** [comment]
[Review and Perspectives on Driver Digital Twin and Its Enabling Technologies for Intelligent Vehicles](https://ieeexplore.ieee.org/abstract/document/9847095) (2022)
